- aeternity/aens.py
- aeternity/config.py
- aeternity/contract.py
- aeternity/epoch.py
- aeternity/tests/test_api.py
- aeternity/tests/test_contract.py
Implemented all of the swagger interface calls and also started implementing the contract interface. All those calls have at least one test but some of those tests still fail because the underlying interface is not documented enough to make them work.
However I like having failing tests better than none, this allows us to track progress on this interface.
> Implemented all remaining swagger api calls, implemented contract interface (still unstable)

- aeternity/__main__.py
- aeternity/config.py
- aeternity/tests/test_aens.py
- aeternity/tests/test_oracle.py
- examples/aens_example.py
- examples/oracle_operator_example.py
- examples/oracle_request_example.py
- examples/spend.py
the environment variables are now called:
AE_EXTERNAL_HOST, AE_EXTERNAL_PORT
AE_INTERNAL_HOST, AE_INTERNAL_PORT
AE_WEBSOCKET_HOST, AE_WEBSOCKET_PORT
> Changed Config object: Allow setting host and port individually

- Dockerfile.ci
- Jenkinsfile
> Add basic configuration for jenkins ci

- aeternity/__main__.py
> feat(cli): add payload to the account spend command

- aeternity/channel.py
> feat(state-channels): added leave and shutdown calls

- aeternity/__main__.py
- aeternity/node.py
- aeternity/transactions.py
> add ability to inspect an encoded transaction

- aeternity/identifiers.py
- aeternity/transactions.py
> fix(tx): encode spend tx payload as base64 string prefixed by 'ba'

- aeternity/__main__.py
`--private-key` will be removed in a future release
> refactor(cli): add option --secret-key as alias to --private-key.

- aeternity/channel.py
> feat(state-channels): added a method to trigger transfer update

- aeternity/channel.py
> feat(state-channels): added contract related methods incl. poi

- aeternity/transactions.py
Node version 3.x fixes a bug in contract fee calculation for contracts,
> feat(fee): adjust the fee calculation for contract transactions

- aeternity/__init__.py
- aeternity/__main__.py
- aeternity/aens.py
- aeternity/defaults.py
- aeternity/hashing.py
- aeternity/node.py
- aeternity/openapi.py
- aeternity/transactions.py
- aeternity/utils.py
- tests/conftest.py
- tests/test_aens.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_contract.py
- tests/test_hashing.py
- tests/test_node.py
- tests/test_oracle.py
- tests/test_signing.py
- tests/test_utils.py
add support for lima aens system
#233  #236 #235
> feat(aens): support lima aens model

- .env
- Makefile
- aeternity/__main__.py
- tests/test_api.py
- tests/test_cli.py
add tests to run a full claim and bid from commandline
close #256
> fix(cli): name claim and update commands

- aeternity/aens.py
- tests/test_aens.py
changes internal api to allow 0 to n pointers in name update
relates to #244
> allow to set multiple and custom pointers for a name

- aeternity/hashing.py
* Fix typo in a BLAKE2 hash function name
> Fix typo in hash function

- aeternity/__main__.py
- aeternity/node.py
- tests/test_aens.py
- tests/test_cli.py
> and transfer_by_name, and add spend and transfer by name to cli

- aeternity/compiler.py
- aeternity/contract_native.py
- tests/test_contract_lima.py
- tests/test_contract_native.py
> feat(contracts): transform sophia datatypes to python datatypes

- aeternity/contract.py
- aeternity/contract_native.py
- docs/howto/accounts_signatures.rst
- docs/index.rst
- docs/intro/index.rst
- docs/intro/tutorial02-contracts-call.rst
- docs/intro/tutorial02-contracts-deploy.rst
- docs/intro/tutorial05-cli.rst
- tests/test_contract_native.py
> feat(contracts): check if contract is deployed

- aeternity/__main__.py
- tests/test_tutorial05-contracts.py
> fix(cli): name bid command

- .travis.yml
`TRAVIS_EVENT_TYPE` is not available before the job starts running.
> fix(ci): Fix CI cron jobs

- aeternity/openapi.py
- aeternity/transactions.py
> add fate specific fee calculation for contract calls

- .env
- tests/test_contract_native.py
> fix(compiler): compiler variant decode

- aeternity/contract.py
- aeternity/contract_native.py
- tests/test_contract_native.py
- tests/test_tutorial05-contracts.py
> feat(contracts): contract_native improvements

- aeternity/transactions.py
- docs/howto/amounts.rst
- docs/howto/index.rst
- docs/ref/txobject.rst
- tests/test_node.py
- tests/test_transactions.py
> implement parser for tx data
